(()=>{var i=(...t)=>{(location.hostname.match("local")||window.sessionStorage.unicorn)&&console.log("\u{1F984}:",...t)};document.addEventListener("alpine:init",()=>{Alpine.data("MetadataChecker",()=>({targetUrl:"",status:"idle",showResults:!1,loading:!1,buttonLabel:"Check Website Metadata",previewData:{},metaTags:"",setButtonLabel(){switch(this.status){case"loading":this.buttonLabel="Fetching Website Metadata...";break;case"success":this.buttonLabel="Check Another Website";break;case"error":this.buttonLabel="Try Again with a Different URL";break;default:this.buttonLabel="Check Website Metadata"}},initProcessing(){this.initLoading(),this.fetchPageData()},initLoading(){this.status="loading",this.setButtonLabel(),this.showResults=!1,this.loading=!0},stopLoading(){this.status="idle",this.setButtonLabel(),this.loading=!1},initSuccess(){i("S for Success"),this.status="success",this.setButtonLabel(),this.showResults=!0,this.loading=!1,history.pushState({},"",`?url=${encodeURIComponent(this.targetUrl)}`)},initError(t){this.status="error",this.setButtonLabel(),this.showResults=!1,this.loading=!1,console.error(t)},isValidUrl(t){return/^(http|https):\/\/[^ "]+$/.test(t)},getPreviewImage(t){let e="";switch(t){case"linkedin":case"facebook":e=this.previewData.og["og:image"]||"";break;case"twitter":e=this.previewData.twitter["twitter:image"]||this.previewData.og["og:image"]||"";break;default:break}return e?e.startsWith("//")?`https:${e}`:e.startsWith("/")?`https://${this.previewData.homeUrl}${e}`:e:"/img/nada-og-image.jpg"},escapeHTML(t){return t.replace(/^[ \t]+/gm,"")},generateMetaTags(t){t||(this.metaTags="Metadata not available");let e="";if(Object.keys(t.metadata).length>0){e=this.escapeHTML("<!-- HTML Meta Tags -->");for(let[a,s]of Object.entries(t.metadata))s&&(a==="title"?e+=this.escapeHTML(`
<title>${s}</title>`):a==="canonical"?e+=this.escapeHTML(`
<link rel="canonical" href="${s}">`):e+=this.escapeHTML(`
<meta name="${a}" content="${s}">`))}if(Object.keys(t.og).length>0){e+=this.escapeHTML(`

<!-- Open Graph Meta Tags -->`);for(let[a,s]of Object.entries(t.og))s&&(e+=this.escapeHTML(`
<meta property="${a}" content="${s}">`))}if(Object.keys(t.twitter).length>0){e+=this.escapeHTML(`

<!-- X.com Meta Tags -->`);for(let[a,s]of Object.entries(t.twitter))s&&(e+=this.escapeHTML(`
<meta name="${a}" content="${s}">`))}typeof Prism=="object"&&typeof Prism.highlight=="function"?this.metaTags=Prism.highlight(e,Prism.languages.html,"html"):this.metaTags=e},fetchPageData(){if(!this.isValidUrl(this.targetUrl)){this.initError("Invalid URL provided");return}fetch("https://api.freshjuice.dev/metadata-checker",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetUrl:this.targetUrl})}).then(t=>{if(!t.ok)throw new Error(`HTTP error! status: ${t.status}`);return t.json()}).then(t=>{this.previewData=t,this.generateMetaTags(t),i("Response Data:",t),this.initSuccess()}).catch(t=>{this.initError(t)})},cleanDomain(){return(this.previewData.homeUrl||"").toLowerCase().replace(/^www\./i,"")},reset(){history.pushState({},"","/tools/metadata-checker/"),this.showResults=!1,this.targetUrl="",this.previewData={},this.metaTags="",this.$refs.targetUrl.focus()},init(){i("Metadata Checker initialized");let e=new URLSearchParams(window.location.search).get("url");e&&(this.targetUrl=e,this.initProcessing())}}))});})();
